"""Sorgu sınıflandırıcı için eğitim verisi."""

MEDICAL_QUERIES = [
    # Metformin
    "What are the side effects of metformin?",
    "Can I take metformin with alcohol?",
    "Metformin drug interactions with NSAIDs",
    "Is metformin safe during pregnancy?",
    "How does metformin affect kidney function?",
    "Metformin contraindications in elderly",
    "What is the maximum dose of metformin?",
    "Can metformin cause lactic acidosis?",
    "Metformin and vitamin B12 deficiency",
    "Switching from metformin to insulin",
    "Metformin for PCOS treatment",
    "Does metformin cause weight loss?",
    "Metformin extended release vs regular",
    "Can diabetics take metformin long term?",
    "Metformin and contrast dye interactions",
    # Warfarin
    "What foods should I avoid with warfarin?",
    "Warfarin and aspirin interaction",
    "How to manage warfarin bleeding risk?",
    "INR target range for warfarin",
    "Warfarin dosing in elderly patients",
    "Can I take ibuprofen with warfarin?",
    "Warfarin reversal for emergency surgery",
    "Vitamin K and warfarin interaction",
    "Warfarin alternatives for atrial fibrillation",
    "How often to check INR on warfarin?",
    "Warfarin and antibiotics",
    "Can warfarin cause hair loss?",
    "Warfarin in pregnancy",
    "Starting dose of warfarin",
    "Warfarin and cranberry juice",
    # Pediatric fever
    "When should I take my child to ER for fever?",
    "Safe fever medications for infants",
    "Pediatric fever management at home",
    "Acetaminophen dosing for children",
    "Fever in 3 month old baby",
    "How high is too high for child fever?",
    "Ibuprofen vs acetaminophen for kids",
    "Febrile seizures in children",
    "Signs of serious infection in feverish child",
    "Lukewarm bath for child fever",
    "Fever after vaccination in infants",
    "Teething and fever",
    "When is child fever an emergency?",
    "Pediatric fever dehydration signs",
    "Antibiotic use for pediatric fever",
    # Genel tıbbi
    "What causes chest pain?",
    "Symptoms of diabetes",
    "How to treat high blood pressure?",
    "Signs of stroke",
    "Anaphylaxis treatment",
    "COVID-19 symptoms in adults",
    "What is sepsis?",
    "Heart attack warning signs",
    "Asthma inhaler types",
    "Pneumonia treatment guidelines",
    "Appendicitis symptoms",
    "Migraine medications",
    "Kidney stone pain management",
    "Depression treatment options",
    "Thyroid disorder symptoms",
    "Arthritis pain relief",
    "Allergic reaction treatment",
    "Blood pressure medications side effects",
    "Cholesterol lowering drugs",
    "Antidepressant withdrawal",
]

NON_MEDICAL_QUERIES = [
    "What's the weather today?",
    "How to cook pasta?",
    "Best movies of 2024",
    "How to learn Python programming?",
    "What time is it in Tokyo?",
    "Recipe for chocolate cake",
    "How to train a dog?",
    "Best laptops for gaming",
    "How to change a tire?",
    "What is the capital of France?",
    "How to tie a tie?",
    "Football match results",
    "How to invest in stocks?",
    "Best restaurants near me",
    "How to write a resume?",
    "Travel tips for Europe",
    "How to fix a leaky faucet?",
    "Best books to read",
    "How to learn Spanish?",
    "Gardening tips for beginners",
    "How to play guitar?",
    "Weather forecast tomorrow",
    "How to bake bread?",
    "Car maintenance tips",
    "How to save money?",
    "Best hiking trails",
    "How to start a business?",
    "Cooking tips for beginners",
    "How to meditate?",
    "Photography basics",
    "How to lose weight naturally?",
    "Best coffee brands",
    "How to improve memory?",
    "Yoga for beginners",
    "How to plant tomatoes?",
    "Top tourist attractions",
    "How to write a book?",
    "Best TV shows Netflix",
    "How to learn chess?",
    "Smartphone comparison",
    "How to make soap?",
    "Bitcoin price today",
    "How to paint walls?",
    "Best running shoes",
    "How to sleep better?",
    "Knitting patterns",
    "How to do laundry?",
    "Car rental tips",
    "How to brew beer?",
    "Dance lessons online",
]

def get_training_data():
    texts = MEDICAL_QUERIES + NON_MEDICAL_QUERIES
    labels = [1] * len(MEDICAL_QUERIES) + [0] * len(NON_MEDICAL_QUERIES)
    return texts, labels
